type Party {
	owner: String!
	code: Int!
	playlist: [String]
	fallbackPlaylist: String!
	users: [String]
	accessToken: String!
	refreshToken: String!
}

type Query {
	findPartyByOwner(owner: String!): Party
	findPartyByCode(code: Int!): Party
	findPartyByOwnerAndCode(owner: String!, code: Int!): Party
	party: Party
}
